const WorkItems = [
	{
		id: 1,
		image: require('../../images/work/bathroom.jpg'),
		imgAlt: 'perfekt-plumb logo',
		href: 'https://www.perfekt-plumb.company',
		title: 'Perfekt',
		desc: 'Online store',
		hashtag: '#SinglePageApplication',
	},
	{
		id: 2,
		image: require('../../images/work/v-r.jpg'),
		imgAlt: 'image',
		href: 'https://mirvr.com.ua',
		title: 'MirVR',
		desc: 'Virtual reality',
		hashtag: '#LandingPage',
	},
	{
		id: 3,
		image: require('../../images/work/fly.jpg'),
		imgAlt: 'flysim logo',
		href: 'https://flysim.com.ua',
		title: 'FlySim',
		desc: 'Anyone can be a pilot!',
		hashtag: '#LandingPage',
	},
	{
		id: 4,
		image: require('../../images/work/smart-building.jpg'),
		imgAlt: 'kambio logo',
		href: 'https://www.kambio.ua/uk',
		title: 'Kambio',
		desc: 'Low-rise construction plant',
		hashtag: '#LandingPage',
	},
	{
		id: 5,
		image: require('../../images/work/lit-hotel.jpg'),
		imgAlt: 'lit-inn logo',
		href: 'https://lit-inn.com',
		title: 'LIT-INN',
		desc: 'LIT-INN is more than hotel',
		hashtag: '#LandingPage',
	},
	{
		id: 6,
		image: require('../../images/work/star-wars.jpg'),
		imgAlt: 'star wars logo',
		href: 'https://star-wars-nao.vercel.app/',
		title: 'Star Wars',
		desc: 'Star Wars Heroes info',
		hashtag: '#SinglePageApplication',
	},
];

export default WorkItems;
